name: release-assets

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  assets:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: "secryst:jsexec"
      SKIP_JS: "1"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          working-directory: ./ruby
      - name: Generate visualization json
        run: pushd ruby; bundle exec rake generate_visualization_json; popd
      - name: Archive json files from the previous step
        uses: thedoctor0/zip-release@master
        with:
          filename: 'vis_json.zip'
          path: ./*.json
          directory: ./ruby/vis_json/
          exclusions: '*.git*'
          type: zip
      - name: Upload artifacts
        id: upload_vis_json
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ruby/vis_json/*.json
          file_glob: true
          tag: v2.1.0b5
          overwrite: true
          body: "visualize json of map systems"
      - name: Generate metadata
        run: pushd ruby; bundle exec rake generate_metadata_json; popd
      - name: Upload metadata
        id: upload_metadata
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ruby/metadata.json
          asset_name: metadata.json
          tag: v2.1.0b5
          overwrite: true
          body: "metadata of all systems"
      - name: Output link
        run: |
          echo ${{ steps.upload_vis_json.outputs.browser_download_url }}
          echo ${{ steps.upload_metadata.outputs.browser_download_url }}
#        - name: Trigger interscript.org
#          uses: peter-evans/repository-dispatch@v1
#          with:
#            token: ${{ secrets.INTERSCRIPT_CI_TOKEN }}
#            repository: interscript/interscript.org
#            event-type: ${{ github.repository }}
#            client-payload: '{ "ref": "${{ github.ref }}" }'
