name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
          architecture: 'x64'

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # For now let's install without secryst, as we don't necessarily need it.
      # We may need to change it once we start to depend on secryst maps.
      - run: pushd ruby && bundle install --jobs 4 --retry 3 --with jsexec --without secryst && popd

      - name: Test the Ruby package
        run: pushd ruby && bundle exec rake && popd

      - name: Test the JS package
        run: pushd js && npm install && npm run prepareMaps && npm test && popd

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.INTERSCRIPT_RUBYGEMS_API_KEY}}
        run: |
          gem install gem-release
          touch ~/.gem/credentials
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          pushd js
          git status
          popd
          pushd maps
          git status
          gem release
          popd
          pushd ruby
          git status
          gem release
          popd
      - name: Publish to npmjs.org
        env:
          NPMJS_TOKEN: ${{secrets.INTERSCRIPT_NPM_TOKEN}}
        run: |
          pushd js
          npm config set //registry.npmjs.org/:_authToken=$NPMJS_TOKEN
          npm run prepareMaps
          npm publish
          popd

      # Let's keep it commented out for now. Please uncomment it once you are ready with
      # interscript-api to support Interscript v2.
      #
      #- name: Trigger interscript-api
      #  uses: peter-evans/repository-dispatch@v1
      #  with:
      #    token: ${{ secrets.INTERSCRIPT_CI_PAT_TOKEN }}
      #    repository: interscript/interscript-api
      #    event-type: ${{ github.repository }}
      #    client-payload: '{ "ref": "${{ github.ref }}" }'
  asset:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: "secryst:jsexec"
      SKIP_JS: "1"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          working-directory: ./ruby
      - name: Generate visualization json
        run: pushd ruby; bundle exec rake generate_visualization_json; popd
      - name: Upload artifacts
        id: upload_vis_json
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ruby/vis_json/*.json
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "visualize json of map systems"
      - name: Generate metadata
        run: pushd ruby; bundle exec rake generate_metadata_json; popd
      - name: Upload metadata
        id: upload_metadata
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ruby/metadata.json
          asset_name: metadata.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "metadata of all systems"
      - name: Output link
        run: |
          echo ${{ steps.upload_vis_json.outputs.browser_download_url }}
          echo ${{ steps.upload_metadata.outputs.browser_download_url }}
#        - name: Trigger interscript.org
#          uses: peter-evans/repository-dispatch@v1
#          with:
#            token: ${{ secrets.INTERSCRIPT_CI_TOKEN }}
#            repository: interscript/interscript.org
#            event-type: ${{ github.repository }}
#            client-payload: '{ "ref": "${{ github.ref }}" }'
