name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Run specs on ${{ matrix.os }} ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ["3.0", "2.7", "2.6", "2.5", "2.4"]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: cd ./ruby

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpecs
        run: |
          bundle install --with=jsexec
          bundle exec rspec
